# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4bfd2cec60c2c3f7ddbad0fcbf4839f814a73b0356e6dedc0664f8f4d7574ab2d20f7af95bdbddbe8ef9372a727a1c02995c270ffff1f13d02dd325c9a77896

test:
  secret_key_base: 3b1220494de748146fa14fc71ebc63a540adebebc5f3146ffc117ce1e8cc9ae89ba95d9100332494f4a8dec437be8f72187fb0eda0cbccb013af283ab032e55f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
